Rename everything from "codimd" to "hedgedoc"
hedgedoc/cli pull request #40
Opened 2020-11-09 20:01 UTC by mrdrogdrog

This PR renames the tool and changes (almost) every occurrence of the word "codimd" to "hedgedoc". See https://github.com/codimd/server/pull/453 for more details.

2020-11-09 20:34 UTC, davidmehren approved these changes

2020-11-09 20:43 UTC, ErikMichelson approved these changes

2020-11-09 20:48 UTC, mrdrogdrog commented
This PR should be merged after codimd/server#453

2020-11-10 17:24 UTC, SISheogorath requested changes
We might want to consider adding a compatibility layer? As this will break existing configs.

2020-11-10 17:24 UTC, SISheogorath commented on README.md
> +*There is an alternative, TypeScript-based HedgeDoc CLI for `hackmdio/codimd` maintained by the HackMD team here: https://github.com/hackmdio/codimd-cli.*
This should still be called CodiMD though

2020-11-15 14:14 UTC, mrdrogdrog commented on README.md
> +*There is an alternative, TypeScript-based HedgeDoc CLI for `hackmdio/codimd` maintained by the HackMD team here: https://github.com/hackmdio/codimd-cli.*
Done

2020-11-15 14:15 UTC, mrdrogdrog commented
A compatibility layer sounds good, but I'm don't want to mess with the bash.

2020-11-15 17:08 UTC, ErikMichelson commented
Compatibility layer in terms of not renaming/symlinking the binary and defining the CODIMD_ environment variables as fallback?

2020-12-15 19:05 UTC, davidmehren commented
@SISheogorath Are you fine with these changes?

2020-12-16 03:22 UTC, pirate approved these changes

2020-12-16 17:15 UTC, SISheogorath requested changes
We definitely need to adjust a few more things and move/migrate configs.

2020-12-16 17:15 UTC, SISheogorath commented on README.md
> +*(it may or may not be compatible with the `hedgedoc/server` server)*
This should be hedgedoc/hedgedoc

2020-12-16 17:15 UTC, SISheogorath commented on README.md
> +$ export HEDGEDOC_COOKIES_FILE=~/.config/codimd-cli/key.conf
We don't want to adjust the config path?

2020-12-16 17:15 UTC, SISheogorath commented on bin/hedgedoc
> +HEDGEDOC_CONFIG_DIR="${HEDGEDOC_CONFIG_DIR:-$XDG_CONFIG_HOME/$SCRIPTNAME}"
This will relocate the config file alresdy, we might want to add a migration function for the config.

2020-12-16 20:23 UTC, mrdrogdrog commented on README.md
> +*(it may or may not be compatible with the `hedgedoc/server` server)*
done

2020-12-16 20:23 UTC, mrdrogdrog commented on README.md
> +$ export HEDGEDOC_COOKIES_FILE=~/.config/codimd-cli/key.conf
done

2020-12-16 20:27 UTC, mrdrogdrog commented on bin/hedgedoc
> +HEDGEDOC_CONFIG_DIR="${HEDGEDOC_CONFIG_DIR:-$XDG_CONFIG_HOME/$SCRIPTNAME}"
The config is already incompatible because all the variable names have been changed.

2020-12-16 20:27 UTC, mrdrogdrog commented on bin/hedgedoc
> +HEDGEDOC_CONFIG_DIR="${HEDGEDOC_CONFIG_DIR:-$XDG_CONFIG_HOME/$SCRIPTNAME}"
I won't write a migration function because I hate bash scripting. If we want a migration then someone else can write it.

2020-12-21 20:41 UTC, SISheogorath commented on bin/hedgedoc
> +HEDGEDOC_CONFIG_DIR="${HEDGEDOC_CONFIG_DIR:-$XDG_CONFIG_HOME/$SCRIPTNAME}"
👀 Well… Since it's only used for the key.conf which is managed by curl, it's not more than moving a directory.

```suggestion
OLD_CODIMD_CONFIG_DIR="${HEDGEDOC_CONFIG_DIR:-$XDG_CONFIG_HOME/codimd}"
HEDGEDOC_CONFIG_DIR="${HEDGEDOC_CONFIG_DIR:-$XDG_CONFIG_HOME/$SCRIPTNAME}"

[ -e "$OLD_CODIMD_CONFIG_DIR" ] && [ ! -e "$HEDGEDOC_CONFIG_DIR" ] && mv "$OLD_CODIMD_CONFIG_DIR" "$HEDGEDOC_CONFIG_DIR"
```

2020-12-27 14:50 UTC, mrdrogdrog commented on bin/hedgedoc
> +HEDGEDOC_CONFIG_DIR="${HEDGEDOC_CONFIG_DIR:-$XDG_CONFIG_HOME/$SCRIPTNAME}"
Then you can create a new PR for the migration. I won't add one.

2020-12-27 18:43 UTC, SISheogorath approved these changes

2020-12-27 21:43 UTC, merged