Added getting metadata from a note id
hedgedoc/cli pull request #53
Opened 2023-02-20 21:04 UTC by darkdecoy

Added getting metadata from a note id
Updated help menu and example for info command
Add json format option to info command

2023-02-21 12:26 UTC, ErikMichelson commented
Hey @darkdecoy,
thanks for your contribution!

In order to get this merged, we need you to sign-off your commits according to the contribution guidelines for the HedgeDoc organization. You can find more information on this here: https://github.com/hedgedoc/hedgedoc/blob/develop/CONTRIBUTING.md#certificate-of-origin

2023-02-21 16:15 UTC, darkdecoy commented
Added a sign off to each commit.

2023-03-06 14:37 UTC, ErikMichelson requested changes
The files from the export folder should not be committed as well

2023-03-06 14:37 UTC, ErikMichelson commented on bin/hedgedoc
> +        View the metadata for a given note on the server.
This seems to be duplicated

2023-03-06 14:37 UTC, ErikMichelson commented on bin/hedgedoc
> +<<<<<<< HEAD
Here are some merge conflict markers, that shouldn't be committed

2023-03-06 23:22 UTC, darkdecoy commented
made the requested changed

2023-03-06 23:59 UTC, closed without merging